service: bookshelf-client
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-northeast-1
  environment:
    API_BASE_URL: ${param:apiBaseUrl}
  
package:
  patterns:
    - '!**'
    - '.output/**'

functions:
  NuxtSsrEngine:
    handler: .output/server/index.handler
    url: true

