service: bookshelf-client
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-northeast-1
  environment:
    API_BASE_URL: ${param:apiBaseUrl}

package:
  patterns:
    - "!**"
    - ".output/**"

functions:
  NuxtSsrEngine:
    handler: .output/server/index.handler
    url: true

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: bookshelf-nuxt
      localDir: .output/public
      deleteRemoved: true

resources:
  Resources:
    StaticResourceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bookshelf-nuxt
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
    StaticResourceOriginAccessControl:
      Type: AWS::CloudFront::OriginAccessControl
      Properties:
        OriginAccessControlConfig:
          Name: "bookshelf-oac"
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4
    StaticResourceBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref StaticResourceBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${StaticResourceBucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${NuxtSampleAppDistribution}"
    NuxtSampleAppDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          HttpVersion: http2
          CacheBehaviors:
            - PathPattern: "/_nuxt/*"
              TargetOriginId: "bookshelf-static-assets"
              ViewerProtocolPolicy: redirect-to-https
              CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          DefaultCacheBehavior:
            TargetOriginId: "nuxt-ssr-engine"
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            ViewerProtocolPolicy: redirect-to-https
          Origins:
            - Id: "bookshelf-static-assets"
              DomainName: !GetAtt StaticResourceBucket.RegionalDomainName
              OriginAccessControlId: !GetAtt StaticResourceOriginAccessControl.Id
              S3OriginConfig: {}
            - Id: "nuxt-ssr-engine"
              DomainName:
                !Select [
                  2,
                  !Split [
                    "/",
                    !GetAtt NuxtSsrEngineLambdaFunctionUrl.FunctionUrl,
                  ],
                ]
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
