service: bookshelf
frameworkVersion: '3'
provider:
  name: aws
  stage: dev
  region: ap-northeast-1

package:
  patterns:
    - '!**'
    - '.output/server/**'

functions:
  NuxtSsrEngine:
    runtime: nodejs16.x
    handler: '.output/server/index.handler'
    url: true
