service: bookshelf-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-northeast-1
  environment:
    booksTableName:
      Ref: booksTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: !GetAtt booksTable.Arn

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline

package:
  individually: true
  patterns:
    - "!**"
    - "**"
    - "!node_modules/**"
  excludeDevDependencies: true

functions:
  Api:
    handler: server.handler
    events:
      - http: ANY api/{proxy+}

custom:
  esbuild:
    bundle: true
    minify: false
  dynamodb:
    stages:
      - dev
    start:
      port: 3004
      migrate: true

resources:
  Resources:
    booksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: books
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  Outputs:
    apiBaseUrl:
      Value:
        {
          "Fn::Join":
            [
              "",
              [
                "https://",
                { "Ref": "ApiGatewayRestApi" },
                ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}",
              ],
            ],
        }
