service: bookshelf-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-northeast-1
  environment:
    API_BASE_URL: { 'Fn::Join': [
      '', [
        'https://',
        {'Ref': 'ApiGatewayRestApi' },
        '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}'
      ]
    ]}

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline


package:
  individually: true
  patterns:
    - '!**'
    - '**'
    - 'node_modules/**'

functions:
  Api:
    handler: server.handler
    events:
      - http: ANY api/{proxy+}

custom:
  esbuild:
    bundle: true
    minify: false
  dynamodb:
    stages:
      - dev
    


resources:
  Resources: 
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: booksTable
        AttributeDefinitions:
          - AttributeName: titleTimestamp
            AttributeType: S
        KeySchema:
          - AttributeName: titleTimestamp
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  Outputs:
    apiBaseUrl:
      Value: { 'Fn::Join': [
        '', [
          'https://',
          {'Ref': 'ApiGatewayRestApi' },
          '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}'
        ]
      ]}