name: tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          dbPath: # undefined by default, if this is undefined inMemory will be used
          sharedDb: # undefined by default
          delayTransientStatuses: # undefined by default
          optimizeDbBeforeStartup: # undefined by default
          port: 8000
          cors: '*'
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install modules
        run: cd server && npm i
      - name: Run tests
        run: cd server && npm run test --runInBand
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
