name: reviewdog
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 3004
          cors: '*'

      - name: Install modules
        run: cd server && npm i
      - name: Run tests
        run: cd server ** npm run test --runInBand